\c alexandrie;

-- Create a temporary table to hold the data and generated ISBNs
CREATE TEMP TABLE temp_livres_data (
    isbn VARCHAR(13),
    auteur_nom VARCHAR(255),
    titre VARCHAR(255),
    annee INT,
    categorie VARCHAR(100),
    editeur VARCHAR(100)
);

-- Insert raw data
WITH raw_data (auteur_nom, titre, annee, categorie, editeur) AS (
    VALUES
    -- Science Fiction
    ('Isaac Asimov', 'Foundation', 1951, 'Science Fiction', 'Gallimard'),
    ('Isaac Asimov', 'I, Robot', 1950, 'Science Fiction', 'J''ai Lu'),
    ('Isaac Asimov', 'The Caves of Steel', 1954, 'Science Fiction', 'J''ai Lu'),
    ('Isaac Asimov', 'The Naked Sun', 1957, 'Science Fiction', 'J''ai Lu'),
    ('Isaac Asimov', 'The Gods Themselves', 1972, 'Science Fiction', 'Gallimard'),
    ('Philip K. Dick', 'Do Androids Dream of Electric Sheep?', 1968, 'Science Fiction', 'J''ai Lu'),
    ('Philip K. Dick', 'Ubik', 1969, 'Science Fiction', '10/18'),
    ('Philip K. Dick', 'The Man in the High Castle', 1962, 'Science Fiction', 'J''ai Lu'),
    ('Philip K. Dick', 'A Scanner Darkly', 1977, 'Science Fiction', '10/18'),
    ('Philip K. Dick', 'Flow My Tears, the Policeman Said', 1974, 'Science Fiction', 'J''ai Lu'),
    ('Frank Herbert', 'Dune', 1965, 'Science Fiction', 'Robert Laffont'),
    ('Frank Herbert', 'Dune Messiah', 1969, 'Science Fiction', 'Robert Laffont'),
    ('Frank Herbert', 'Children of Dune', 1976, 'Science Fiction', 'Robert Laffont'),
    ('Frank Herbert', 'God Emperor of Dune', 1981, 'Science Fiction', 'Robert Laffont'),
    ('Frank Herbert', 'Heretics of Dune', 1984, 'Science Fiction', 'Robert Laffont'),
    ('Arthur C. Clarke', '2001: A Space Odyssey', 1968, 'Science Fiction', 'J''ai Lu'),
    ('Arthur C. Clarke', 'Rendezvous with Rama', 1973, 'Science Fiction', 'J''ai Lu'),
    ('Arthur C. Clarke', 'Childhood''s End', 1953, 'Science Fiction', 'J''ai Lu'),
    ('Arthur C. Clarke', 'The City and the Stars', 1956, 'Science Fiction', 'J''ai Lu'),
    ('Arthur C. Clarke', 'The Fountains of Paradise', 1979, 'Science Fiction', 'J''ai Lu'),
    ('H.G. Wells', 'The Time Machine', 1895, 'Science Fiction', 'Folio'),
    ('H.G. Wells', 'The War of the Worlds', 1898, 'Science Fiction', 'Folio'),
    ('H.G. Wells', 'The Invisible Man', 1897, 'Science Fiction', 'Folio'),
    ('H.G. Wells', 'The Island of Doctor Moreau', 1896, 'Science Fiction', 'Folio'),
    ('H.G. Wells', 'The First Men in the Moon', 1901, 'Science Fiction', 'Folio'),
    ('Ray Bradbury', 'Fahrenheit 451', 1953, 'Science Fiction', 'Denoël'),
    ('Ray Bradbury', 'The Martian Chronicles', 1950, 'Science Fiction', 'Denoël'),
    ('Ray Bradbury', 'The Illustrated Man', 1951, 'Science Fiction', 'Denoël'),
    ('Ray Bradbury', 'Something Wicked This Way Comes', 1962, 'Science Fiction', 'Denoël'),
    ('Ray Bradbury', 'Dandelion Wine', 1957, 'Science Fiction', 'Denoël'),
    ('George Orwell', '1984', 1949, 'Science Fiction', 'Gallimard'),
    ('George Orwell', 'Animal Farm', 1945, 'Science Fiction', 'Gallimard'),
    ('George Orwell', 'Homage to Catalonia', 1938, 'Science Fiction', 'Gallimard'),
    ('George Orwell', 'Down and Out in Paris and London', 1933, 'Science Fiction', 'Gallimard'),
    ('George Orwell', 'The Road to Wigan Pier', 1937, 'Science Fiction', 'Gallimard'),
    ('Aldous Huxley', 'Brave New World', 1932, 'Science Fiction', 'Pocket'),
    ('Aldous Huxley', 'Island', 1962, 'Science Fiction', 'Pocket'),
    ('Aldous Huxley', 'Point Counter Point', 1928, 'Science Fiction', 'Pocket'),
    ('Aldous Huxley', 'The Doors of Perception', 1954, 'Science Fiction', 'Pocket'),
    ('Aldous Huxley', 'Crome Yellow', 1921, 'Science Fiction', 'Pocket'),
    ('William Gibson', 'Neuromancer', 1984, 'Science Fiction', 'J''ai Lu'),
    ('William Gibson', 'Count Zero', 1986, 'Science Fiction', 'J''ai Lu'),
    ('William Gibson', 'Mona Lisa Overdrive', 1988, 'Science Fiction', 'J''ai Lu'),
    ('William Gibson', 'Virtual Light', 1993, 'Science Fiction', 'J''ai Lu'),
    ('William Gibson', 'Idoru', 1996, 'Science Fiction', 'J''ai Lu'),
    ('Ursula K. Le Guin', 'The Left Hand of Darkness', 1969, 'Science Fiction', 'Livre de Poche'),
    ('Ursula K. Le Guin', 'The Dispossessed', 1974, 'Science Fiction', 'Livre de Poche'),
    ('Ursula K. Le Guin', 'A Wizard of Earthsea', 1968, 'Fantasy', 'Livre de Poche'),
    ('Ursula K. Le Guin', 'The Tombs of Atuan', 1971, 'Fantasy', 'Livre de Poche'),
    ('Ursula K. Le Guin', 'The Farthest Shore', 1972, 'Fantasy', 'Livre de Poche'),

    -- Fantasy
    ('J.R.R. Tolkien', 'The Fellowship of the Ring', 1954, 'Fantasy', 'Christian Bourgois'),
    ('J.R.R. Tolkien', 'The Two Towers', 1954, 'Fantasy', 'Christian Bourgois'),
    ('J.R.R. Tolkien', 'The Return of the King', 1955, 'Fantasy', 'Christian Bourgois'),
    ('J.R.R. Tolkien', 'The Hobbit', 1937, 'Fantasy', 'Christian Bourgois'),
    ('J.R.R. Tolkien', 'The Silmarillion', 1977, 'Fantasy', 'Christian Bourgois'),
    ('J.K. Rowling', 'Harry Potter and the Philosopher''s Stone', 1997, 'Fantasy', 'Gallimard Jeunesse'),
    ('J.K. Rowling', 'Harry Potter and the Chamber of Secrets', 1998, 'Fantasy', 'Gallimard Jeunesse'),
    ('J.K. Rowling', 'Harry Potter and the Prisoner of Azkaban', 1999, 'Fantasy', 'Gallimard Jeunesse'),
    ('J.K. Rowling', 'Harry Potter and the Goblet of Fire', 2000, 'Fantasy', 'Gallimard Jeunesse'),
    ('J.K. Rowling', 'Harry Potter and the Order of the Phoenix', 2003, 'Fantasy', 'Gallimard Jeunesse'),
    ('George R.R. Martin', 'A Game of Thrones', 1996, 'Fantasy', 'Pygmalion'),
    ('George R.R. Martin', 'A Clash of Kings', 1998, 'Fantasy', 'Pygmalion'),
    ('George R.R. Martin', 'A Storm of Swords', 2000, 'Fantasy', 'Pygmalion'),
    ('George R.R. Martin', 'A Feast for Crows', 2005, 'Fantasy', 'Pygmalion'),
    ('George R.R. Martin', 'A Dance with Dragons', 2011, 'Fantasy', 'Pygmalion'),
    ('Terry Pratchett', 'The Colour of Magic', 1983, 'Fantasy', 'L''Atalante'),
    ('Terry Pratchett', 'The Light Fantastic', 1986, 'Fantasy', 'L''Atalante'),
    ('Terry Pratchett', 'Equal Rites', 1987, 'Fantasy', 'L''Atalante'),
    ('Terry Pratchett', 'Mort', 1987, 'Fantasy', 'L''Atalante'),
    ('Terry Pratchett', 'Sourcery', 1988, 'Fantasy', 'L''Atalante'),
    ('C.S. Lewis', 'The Lion, the Witch and the Wardrobe', 1950, 'Fantasy', 'Gallimard Jeunesse'),
    ('C.S. Lewis', 'Prince Caspian', 1951, 'Fantasy', 'Gallimard Jeunesse'),
    ('C.S. Lewis', 'The Voyage of the Dawn Treader', 1952, 'Fantasy', 'Gallimard Jeunesse'),
    ('C.S. Lewis', 'The Silver Chair', 1953, 'Fantasy', 'Gallimard Jeunesse'),
    ('C.S. Lewis', 'The Horse and His Boy', 1954, 'Fantasy', 'Gallimard Jeunesse'),
    ('Neil Gaiman', 'American Gods', 2001, 'Fantasy', 'Au Diable Vauvert'),
    ('Neil Gaiman', 'Coraline', 2002, 'Fantasy', 'Albin Michel'),
    ('Neil Gaiman', 'Stardust', 1999, 'Fantasy', 'J''ai Lu'),
    ('Neil Gaiman', 'Neverwhere', 1996, 'Fantasy', 'J''ai Lu'),
    ('Neil Gaiman', 'The Graveyard Book', 2008, 'Fantasy', 'Albin Michel'),
    ('Robin Hobb', 'Assassin''s Apprentice', 1995, 'Fantasy', 'Pygmalion'),
    ('Robin Hobb', 'Royal Assassin', 1996, 'Fantasy', 'Pygmalion'),
    ('Robin Hobb', 'Assassin''s Quest', 1997, 'Fantasy', 'Pygmalion'),
    ('Robin Hobb', 'Ship of Magic', 1998, 'Fantasy', 'Pygmalion'),
    ('Robin Hobb', 'Mad Ship', 1999, 'Fantasy', 'Pygmalion'),
    ('Patrick Rothfuss', 'The Name of the Wind', 2007, 'Fantasy', 'Bragelonne'),
    ('Patrick Rothfuss', 'The Wise Man''s Fear', 2011, 'Fantasy', 'Bragelonne'),
    ('Patrick Rothfuss', 'The Slow Regard of Silent Things', 2014, 'Fantasy', 'Bragelonne'),
    ('Patrick Rothfuss', 'The Lightning Tree', 2014, 'Fantasy', 'Bragelonne'),
    ('Patrick Rothfuss', 'How Old Holly Came to Be', 2013, 'Fantasy', 'Bragelonne'),
    ('Brandon Sanderson', 'Mistborn: The Final Empire', 2006, 'Fantasy', 'Livre de Poche'),
    ('Brandon Sanderson', 'The Well of Ascension', 2007, 'Fantasy', 'Livre de Poche'),
    ('Brandon Sanderson', 'The Hero of Ages', 2008, 'Fantasy', 'Livre de Poche'),
    ('Brandon Sanderson', 'The Way of Kings', 2010, 'Fantasy', 'Livre de Poche'),
    ('Brandon Sanderson', 'Words of Radiance', 2014, 'Fantasy', 'Livre de Poche'),
    ('Andrzej Sapkowski', 'The Last Wish', 1993, 'Fantasy', 'Bragelonne'),
    ('Andrzej Sapkowski', 'Sword of Destiny', 1992, 'Fantasy', 'Bragelonne'),
    ('Andrzej Sapkowski', 'Blood of Elves', 1994, 'Fantasy', 'Bragelonne'),
    ('Andrzej Sapkowski', 'Time of Contempt', 1995, 'Fantasy', 'Bragelonne'),
    ('Andrzej Sapkowski', 'Baptism of Fire', 1996, 'Fantasy', 'Bragelonne'),

    -- Policier / Thriller
    ('Agatha Christie', 'And Then There Were None', 1939, 'Policier', 'Livre de Poche'),
    ('Agatha Christie', 'Murder on the Orient Express', 1934, 'Policier', 'Livre de Poche'),
    ('Agatha Christie', 'The Murder of Roger Ackroyd', 1926, 'Policier', 'Livre de Poche'),
    ('Agatha Christie', 'Death on the Nile', 1937, 'Policier', 'Livre de Poche'),
    ('Agatha Christie', 'The ABC Murders', 1936, 'Policier', 'Livre de Poche'),
    ('Arthur Conan Doyle', 'A Study in Scarlet', 1887, 'Policier', 'Livre de Poche'),
    ('Arthur Conan Doyle', 'The Sign of Four', 1890, 'Policier', 'Livre de Poche'),
    ('Arthur Conan Doyle', 'The Hound of the Baskervilles', 1902, 'Policier', 'Livre de Poche'),
    ('Arthur Conan Doyle', 'The Valley of Fear', 1915, 'Policier', 'Livre de Poche'),
    ('Arthur Conan Doyle', 'The Adventures of Sherlock Holmes', 1892, 'Policier', 'Livre de Poche'),
    ('Georges Simenon', 'Pietr-le-Letton', 1931, 'Policier', 'Presses de la Cité'),
    ('Georges Simenon', 'Le Chien jaune', 1931, 'Policier', 'Presses de la Cité'),
    ('Georges Simenon', 'La Tête d''un homme', 1931, 'Policier', 'Presses de la Cité'),
    ('Georges Simenon', 'L''Affaire Saint-Fiacre', 1932, 'Policier', 'Presses de la Cité'),
    ('Georges Simenon', 'Maigret tend un piège', 1955, 'Policier', 'Presses de la Cité'),
    ('Raymond Chandler', 'The Big Sleep', 1939, 'Policier', 'Gallimard'),
    ('Raymond Chandler', 'Farewell, My Lovely', 1940, 'Policier', 'Gallimard'),
    ('Raymond Chandler', 'The High Window', 1942, 'Policier', 'Gallimard'),
    ('Raymond Chandler', 'The Lady in the Lake', 1943, 'Policier', 'Gallimard'),
    ('Raymond Chandler', 'The Long Goodbye', 1953, 'Policier', 'Gallimard'),
    ('Fred Vargas', 'L''Homme aux cercles bleus', 1991, 'Policier', 'Viviane Hamy'),
    ('Fred Vargas', 'L''Homme à l''envers', 1999, 'Policier', 'Viviane Hamy'),
    ('Fred Vargas', 'Pars vite et reviens tard', 2001, 'Policier', 'Viviane Hamy'),
    ('Fred Vargas', 'Sous les vents de Neptune', 2004, 'Policier', 'Viviane Hamy'),
    ('Fred Vargas', 'Dans les bois éternels', 2006, 'Policier', 'Viviane Hamy'),
    ('Jo Nesbø', 'The Bat', 1997, 'Policier', 'Gallimard'),
    ('Jo Nesbø', 'Cockroaches', 1998, 'Policier', 'Gallimard'),
    ('Jo Nesbø', 'The Redbreast', 2000, 'Policier', 'Gallimard'),
    ('Jo Nesbø', 'Nemesis', 2002, 'Policier', 'Gallimard'),
    ('Jo Nesbø', 'The Devil''s Star', 2003, 'Policier', 'Gallimard'),
    ('Stieg Larsson', 'The Girl with the Dragon Tattoo', 2005, 'Thriller', 'Actes Sud'),
    ('Stieg Larsson', 'The Girl Who Played with Fire', 2006, 'Thriller', 'Actes Sud'),
    ('Stieg Larsson', 'The Girl Who Kicked the Hornets'' Nest', 2007, 'Thriller', 'Actes Sud'),
    ('Stieg Larsson', 'The Girl in the Spider''s Web', 2015, 'Thriller', 'Actes Sud'),
    ('Stieg Larsson', 'The Girl Who Takes an Eye for an Eye', 2017, 'Thriller', 'Actes Sud'),
    ('Harlan Coben', 'Tell No One', 2001, 'Thriller', 'Belfond'),
    ('Harlan Coben', 'Gone for Good', 2002, 'Thriller', 'Belfond'),
    ('Harlan Coben', 'No Second Chance', 2003, 'Thriller', 'Belfond'),
    ('Harlan Coben', 'Just One Look', 2004, 'Thriller', 'Belfond'),
    ('Harlan Coben', 'The Innocent', 2005, 'Thriller', 'Belfond'),
    ('Mary Higgins Clark', 'Where Are the Children?', 1975, 'Thriller', 'Albin Michel'),
    ('Mary Higgins Clark', 'A Stranger Is Watching', 1977, 'Thriller', 'Albin Michel'),
    ('Mary Higgins Clark', 'The Cradle Will Fall', 1980, 'Thriller', 'Albin Michel'),
    ('Mary Higgins Clark', 'A Cry in the Night', 1982, 'Thriller', 'Albin Michel'),
    ('Mary Higgins Clark', 'Stillwatch', 1984, 'Thriller', 'Albin Michel'),
    ('Maurice Leblanc', 'Arsène Lupin, gentleman-cambrioleur', 1907, 'Policier', 'Livre de Poche'),
    ('Maurice Leblanc', 'Arsène Lupin contre Herlock Sholmès', 1908, 'Policier', 'Livre de Poche'),
    ('Maurice Leblanc', 'L''Aiguille creuse', 1909, 'Policier', 'Livre de Poche'),
    ('Maurice Leblanc', '813', 1910, 'Policier', 'Livre de Poche'),
    ('Maurice Leblanc', 'Le Bouchon de cristal', 1912, 'Policier', 'Livre de Poche'),

    -- Horreur / Fantastique
    ('Stephen King', 'Carrie', 1974, 'Horreur', 'Livre de Poche'),
    ('Stephen King', '''Salem''s Lot', 1975, 'Horreur', 'Livre de Poche'),
    ('Stephen King', 'The Shining', 1977, 'Horreur', 'Livre de Poche'),
    ('Stephen King', 'The Stand', 1978, 'Horreur', 'Livre de Poche'),
    ('Stephen King', 'The Dead Zone', 1979, 'Horreur', 'Livre de Poche'),
    ('H.P. Lovecraft', 'The Call of Cthulhu', 1928, 'Horreur', 'Folio SF'),
    ('H.P. Lovecraft', 'The Shadow over Innsmouth', 1936, 'Horreur', 'Folio SF'),
    ('H.P. Lovecraft', 'The Dunwich Horror', 1929, 'Horreur', 'Folio SF'),
    ('H.P. Lovecraft', 'The Colour Out of Space', 1927, 'Horreur', 'Folio SF'),
    ('H.P. Lovecraft', 'At the Mountains of Madness', 1936, 'Horreur', 'Folio SF'),
    ('Edgar Allan Poe', 'The Raven', 1845, 'Fantastique', 'Folio'),
    ('Edgar Allan Poe', 'The Fall of the House of Usher', 1839, 'Fantastique', 'Folio'),
    ('Edgar Allan Poe', 'The Murders in the Rue Morgue', 1841, 'Fantastique', 'Folio'),
    ('Edgar Allan Poe', 'The Masque of the Red Death', 1842, 'Fantastique', 'Folio'),
    ('Edgar Allan Poe', 'The Pit and the Pendulum', 1842, 'Fantastique', 'Folio'),
    ('Bram Stoker', 'Dracula', 1897, 'Horreur', 'J''ai Lu'),
    ('Bram Stoker', 'The Jewel of Seven Stars', 1903, 'Horreur', 'J''ai Lu'),
    ('Bram Stoker', 'The Lady of the Shroud', 1909, 'Horreur', 'J''ai Lu'),
    ('Bram Stoker', 'The Lair of the White Worm', 1911, 'Horreur', 'J''ai Lu'),
    ('Bram Stoker', 'The Mystery of the Sea', 1902, 'Horreur', 'J''ai Lu'),
    ('Mary Shelley', 'Frankenstein', 1818, 'Horreur', 'Folio'),
    ('Mary Shelley', 'The Last Man', 1826, 'Horreur', 'Folio'),
    ('Mary Shelley', 'Valperga', 1823, 'Horreur', 'Folio'),
    ('Mary Shelley', 'Perkin Warbeck', 1830, 'Horreur', 'Folio'),
    ('Mary Shelley', 'Lodore', 1835, 'Horreur', 'Folio'),
    ('Anne Rice', 'Interview with the Vampire', 1976, 'Fantastique', 'Pocket'),
    ('Anne Rice', 'The Vampire Lestat', 1985, 'Fantastique', 'Pocket'),
    ('Anne Rice', 'The Queen of the Damned', 1988, 'Fantastique', 'Pocket'),
    ('Anne Rice', 'The Tale of the Body Thief', 1992, 'Fantastique', 'Pocket'),
    ('Anne Rice', 'Memnoch the Devil', 1995, 'Fantastique', 'Pocket'),
    ('Clive Barker', 'The Hellbound Heart', 1986, 'Horreur', 'Bragelonne'),
    ('Clive Barker', 'Weaveworld', 1987, 'Horreur', 'Bragelonne'),
    ('Clive Barker', 'Imajica', 1991, 'Horreur', 'Bragelonne'),
    ('Clive Barker', 'The Great and Secret Show', 1989, 'Horreur', 'Bragelonne'),
    ('Clive Barker', 'Cabal', 1988, 'Horreur', 'Bragelonne'),
    ('Shirley Jackson', 'The Haunting of Hill House', 1959, 'Horreur', 'Rivages'),
    ('Shirley Jackson', 'We Have Always Lived in the Castle', 1962, 'Horreur', 'Rivages'),
    ('Shirley Jackson', 'The Lottery', 1948, 'Horreur', 'Rivages'),
    ('Shirley Jackson', 'Hangsaman', 1951, 'Horreur', 'Rivages'),
    ('Shirley Jackson', 'The Bird''s Nest', 1954, 'Horreur', 'Rivages'),
    ('Richard Matheson', 'I Am Legend', 1954, 'Horreur', 'J''ai Lu'),
    ('Richard Matheson', 'The Shrinking Man', 1956, 'Horreur', 'J''ai Lu'),
    ('Richard Matheson', 'Hell House', 1971, 'Horreur', 'J''ai Lu'),
    ('Richard Matheson', 'Bid Time Return', 1975, 'Horreur', 'J''ai Lu'),
    ('Richard Matheson', 'What Dreams May Come', 1978, 'Horreur', 'J''ai Lu'),
    ('Guy de Maupassant', 'Le Horla', 1887, 'Fantastique', 'Livre de Poche'),
    ('Guy de Maupassant', 'Boule de Suif', 1880, 'Classique', 'Livre de Poche'),
    ('Guy de Maupassant', 'Une vie', 1883, 'Classique', 'Livre de Poche'),
    ('Guy de Maupassant', 'Bel-Ami', 1885, 'Classique', 'Livre de Poche'),
    ('Guy de Maupassant', 'Pierre et Jean', 1888, 'Classique', 'Livre de Poche'),

    -- Romance
    ('Jane Austen', 'Sense and Sensibility', 1811, 'Romance', 'Folio'),
    ('Jane Austen', 'Pride and Prejudice', 1813, 'Romance', 'Folio'),
    ('Jane Austen', 'Mansfield Park', 1814, 'Romance', 'Folio'),
    ('Jane Austen', 'Emma', 1815, 'Romance', 'Folio'),
    ('Jane Austen', 'Northanger Abbey', 1817, 'Romance', 'Folio'),
    ('Charlotte Brontë', 'Jane Eyre', 1847, 'Romance', 'Livre de Poche'),
    ('Charlotte Brontë', 'Shirley', 1849, 'Romance', 'Livre de Poche'),
    ('Charlotte Brontë', 'Villette', 1853, 'Romance', 'Livre de Poche'),
    ('Charlotte Brontë', 'The Professor', 1857, 'Romance', 'Livre de Poche'),
    ('Charlotte Brontë', 'Tales of Angria', 1934, 'Romance', 'Livre de Poche'),
    ('Emily Brontë', 'Wuthering Heights', 1847, 'Romance', 'Livre de Poche'),
    ('Emily Brontë', 'Poems', 1846, 'Poésie', 'Livre de Poche'),
    ('Emily Brontë', 'Gondal Poems', 1938, 'Poésie', 'Livre de Poche'),
    ('Emily Brontë', 'The Complete Poems', 1941, 'Poésie', 'Livre de Poche'),
    ('Emily Brontë', 'Essays', 1996, 'Essai', 'Livre de Poche'),
    ('Nora Roberts', 'Vision in White', 2009, 'Romance', 'J''ai Lu'),
    ('Nora Roberts', 'Bed of Roses', 2009, 'Romance', 'J''ai Lu'),
    ('Nora Roberts', 'Savor the Moment', 2010, 'Romance', 'J''ai Lu'),
    ('Nora Roberts', 'Happy Ever After', 2010, 'Romance', 'J''ai Lu'),
    ('Nora Roberts', 'Blue Dahlia', 2004, 'Romance', 'J''ai Lu'),
    ('Danielle Steel', 'The Promise', 1978, 'Romance', 'Presses de la Cité'),
    ('Danielle Steel', 'Palomino', 1981, 'Romance', 'Presses de la Cité'),
    ('Danielle Steel', 'The Ring', 1980, 'Romance', 'Presses de la Cité'),
    ('Danielle Steel', 'Family Album', 1985, 'Romance', 'Presses de la Cité'),
    ('Danielle Steel', 'Fine Things', 1987, 'Romance', 'Presses de la Cité'),
    ('Marc Levy', 'Et si c''était vrai...', 2000, 'Romance', 'Robert Laffont'),
    ('Marc Levy', 'Où es-tu ?', 2001, 'Romance', 'Robert Laffont'),
    ('Marc Levy', 'Sept jours pour une éternité...', 2003, 'Romance', 'Robert Laffont'),
    ('Marc Levy', 'La Prochaine Fois', 2004, 'Romance', 'Robert Laffont'),
    ('Marc Levy', 'Vous revoir', 2005, 'Romance', 'Robert Laffont'),
    ('Guillaume Musso', 'Et après...', 2004, 'Romance', 'XO Éditions'),
    ('Guillaume Musso', 'Sauve-moi', 2005, 'Romance', 'XO Éditions'),
    ('Guillaume Musso', 'Seras-tu là ?', 2006, 'Romance', 'XO Éditions'),
    ('Guillaume Musso', 'Parce que je t''aime', 2007, 'Romance', 'XO Éditions'),
    ('Guillaume Musso', 'Je reviens te chercher', 2008, 'Romance', 'XO Éditions'),
    ('Nicholas Sparks', 'The Notebook', 1996, 'Romance', 'Michel Lafon'),
    ('Nicholas Sparks', 'Message in a Bottle', 1998, 'Romance', 'Michel Lafon'),
    ('Nicholas Sparks', 'A Walk to Remember', 1999, 'Romance', 'Michel Lafon'),
    ('Nicholas Sparks', 'The Rescue', 2000, 'Romance', 'Michel Lafon'),
    ('Nicholas Sparks', 'A Bend in the Road', 2001, 'Romance', 'Michel Lafon'),
    ('Margaret Mitchell', 'Gone with the Wind', 1936, 'Romance', 'Gallimard'),
    ('Margaret Mitchell', 'Lost Laysen', 1916, 'Romance', 'Gallimard'),
    ('Margaret Mitchell', 'Before Scarlett', 2000, 'Romance', 'Gallimard'),
    ('Margaret Mitchell', 'The Fitzgeralds and the Kennedys', 2001, 'Romance', 'Gallimard'),
    ('Margaret Mitchell', 'Scarlett', 1991, 'Romance', 'Gallimard'),
    ('George Sand', 'La Mare au diable', 1846, 'Romance', 'Folio'),
    ('George Sand', 'La Petite Fadette', 1849, 'Romance', 'Folio'),
    ('George Sand', 'François le Champi', 1847, 'Romance', 'Folio'),
    ('George Sand', 'Indiana', 1832, 'Romance', 'Folio'),
    ('George Sand', 'Lélia', 1833, 'Romance', 'Folio'),

    -- Littérature Classique
    ('Victor Hugo', 'Les Misérables', 1862, 'Classique', 'Folio'),
    ('Victor Hugo', 'Notre-Dame de Paris', 1831, 'Classique', 'Folio'),
    ('Victor Hugo', 'Les Travailleurs de la mer', 1866, 'Classique', 'Folio'),
    ('Victor Hugo', 'L''Homme qui rit', 1869, 'Classique', 'Folio'),
    ('Victor Hugo', 'Quatre-vingt-treize', 1874, 'Classique', 'Folio'),
    ('Émile Zola', 'L''Assommoir', 1877, 'Classique', 'Livre de Poche'),
    ('Émile Zola', 'Nana', 1880, 'Classique', 'Livre de Poche'),
    ('Émile Zola', 'Germinal', 1885, 'Classique', 'Livre de Poche'),
    ('Émile Zola', 'La Bête humaine', 1890, 'Classique', 'Livre de Poche'),
    ('Émile Zola', 'Au Bonheur des Dames', 1883, 'Classique', 'Livre de Poche'),
    ('Gustave Flaubert', 'Madame Bovary', 1857, 'Classique', 'Folio'),
    ('Gustave Flaubert', 'L''Éducation sentimentale', 1869, 'Classique', 'Folio'),
    ('Gustave Flaubert', 'Salammbô', 1862, 'Classique', 'Folio'),
    ('Gustave Flaubert', 'La Tentation de Saint Antoine', 1874, 'Classique', 'Folio'),
    ('Gustave Flaubert', 'Trois contes', 1877, 'Classique', 'Folio'),
    ('Charles Dickens', 'The Pickwick Papers', 1837, 'Classique', 'Penguin'),
    ('Charles Dickens', 'Oliver Twist', 1838, 'Classique', 'Penguin'),
    ('Charles Dickens', 'Nicholas Nickleby', 1839, 'Classique', 'Penguin'),
    ('Charles Dickens', 'The Old Curiosity Shop', 1841, 'Classique', 'Penguin'),
    ('Charles Dickens', 'David Copperfield', 1850, 'Classique', 'Penguin'),
    ('Léon Tolstoï', 'War and Peace', 1869, 'Classique', 'Gallimard'),
    ('Léon Tolstoï', 'Anna Karenina', 1877, 'Classique', 'Gallimard'),
    ('Léon Tolstoï', 'Resurrection', 1899, 'Classique', 'Gallimard'),
    ('Léon Tolstoï', 'The Death of Ivan Ilyich', 1886, 'Classique', 'Gallimard'),
    ('Léon Tolstoï', 'Hadji Murad', 1912, 'Classique', 'Gallimard'),
    ('Fiodor Dostoïevski', 'Crime and Punishment', 1866, 'Classique', 'Actes Sud'),
    ('Fiodor Dostoïevski', 'The Idiot', 1869, 'Classique', 'Actes Sud'),
    ('Fiodor Dostoïevski', 'Demons', 1872, 'Classique', 'Actes Sud'),
    ('Fiodor Dostoïevski', 'The Brothers Karamazov', 1880, 'Classique', 'Actes Sud'),
    ('Fiodor Dostoïevski', 'Notes from Underground', 1864, 'Classique', 'Actes Sud'),
    ('Marcel Proust', 'Du côté de chez Swann', 1913, 'Classique', 'Gallimard'),
    ('Marcel Proust', 'À l''ombre des jeunes filles en fleurs', 1919, 'Classique', 'Gallimard'),
    ('Marcel Proust', 'Le Côté de Guermantes', 1920, 'Classique', 'Gallimard'),
    ('Marcel Proust', 'Sodome et Gomorrhe', 1921, 'Classique', 'Gallimard'),
    ('Marcel Proust', 'La Prisonnière', 1923, 'Classique', 'Gallimard'),
    ('Honoré de Balzac', 'Le Père Goriot', 1835, 'Classique', 'Livre de Poche'),
    ('Honoré de Balzac', 'Eugénie Grandet', 1833, 'Classique', 'Livre de Poche'),
    ('Honoré de Balzac', 'La Cousine Bette', 1846, 'Classique', 'Livre de Poche'),
    ('Honoré de Balzac', 'Le Cousin Pons', 1847, 'Classique', 'Livre de Poche'),
    ('Honoré de Balzac', 'Illusions perdues', 1837, 'Classique', 'Livre de Poche'),
    ('Ernest Hemingway', 'The Sun Also Rises', 1926, 'Classique', 'Gallimard'),
    ('Ernest Hemingway', 'A Farewell to Arms', 1929, 'Classique', 'Gallimard'),
    ('Ernest Hemingway', 'For Whom the Bell Tolls', 1940, 'Classique', 'Gallimard'),
    ('Ernest Hemingway', 'The Old Man and the Sea', 1952, 'Classique', 'Gallimard'),
    ('Ernest Hemingway', 'A Moveable Feast', 1964, 'Classique', 'Gallimard'),
    ('William Faulkner', 'The Sound and the Fury', 1929, 'Classique', 'Gallimard'),
    ('William Faulkner', 'As I Lay Dying', 1930, 'Classique', 'Gallimard'),
    ('William Faulkner', 'Light in August', 1932, 'Classique', 'Gallimard'),
    ('William Faulkner', 'Absalom, Absalom!', 1936, 'Classique', 'Gallimard'),
    ('William Faulkner', 'A Rose for Emily', 1930, 'Classique', 'Gallimard'),

    -- Fiction Moderne / Contemporaine
    ('Haruki Murakami', 'Norwegian Wood', 1987, 'Fiction', '10/18'),
    ('Haruki Murakami', 'The Wind-Up Bird Chronicle', 1994, 'Fiction', '10/18'),
    ('Haruki Murakami', 'Kafka on the Shore', 2002, 'Fiction', '10/18'),
    ('Haruki Murakami', '1Q84', 2009, 'Fiction', '10/18'),
    ('Haruki Murakami', 'Colorless Tsukuru Tazaki and His Years of Pilgrimage', 2013, 'Fiction', '10/18'),
    ('Gabriel García Márquez', 'One Hundred Years of Solitude', 1967, 'Fiction', 'Grasset'),
    ('Gabriel García Márquez', 'Love in the Time of Cholera', 1985, 'Fiction', 'Grasset'),
    ('Gabriel García Márquez', 'Chronicle of a Death Foretold', 1981, 'Fiction', 'Grasset'),
    ('Gabriel García Márquez', 'The Autumn of the Patriarch', 1975, 'Fiction', 'Grasset'),
    ('Gabriel García Márquez', 'The General in His Labyrinth', 1989, 'Fiction', 'Grasset'),
    ('Milan Kundera', 'The Joke', 1967, 'Fiction', 'Gallimard'),
    ('Milan Kundera', 'Life Is Elsewhere', 1973, 'Fiction', 'Gallimard'),
    ('Milan Kundera', 'The Farewell Waltz', 1972, 'Fiction', 'Gallimard'),
    ('Milan Kundera', 'The Book of Laughter and Forgetting', 1979, 'Fiction', 'Gallimard'),
    ('Milan Kundera', 'The Unbearable Lightness of Being', 1984, 'Fiction', 'Gallimard'),
    ('Paul Auster', 'City of Glass', 1985, 'Fiction', 'Actes Sud'),
    ('Paul Auster', 'Ghosts', 1986, 'Fiction', 'Actes Sud'),
    ('Paul Auster', 'The Locked Room', 1986, 'Fiction', 'Actes Sud'),
    ('Paul Auster', 'Moon Palace', 1989, 'Fiction', 'Actes Sud'),
    ('Paul Auster', 'The Music of Chance', 1990, 'Fiction', 'Actes Sud'),
    ('Philip Roth', 'Goodbye, Columbus', 1959, 'Fiction', 'Gallimard'),
    ('Philip Roth', 'Portnoy''s Complaint', 1969, 'Fiction', 'Gallimard'),
    ('Philip Roth', 'American Pastoral', 1997, 'Fiction', 'Gallimard'),
    ('Philip Roth', 'I Married a Communist', 1998, 'Fiction', 'Gallimard'),
    ('Philip Roth', 'The Human Stain', 2000, 'Fiction', 'Gallimard'),
    ('Toni Morrison', 'The Bluest Eye', 1970, 'Fiction', 'Christian Bourgois'),
    ('Toni Morrison', 'Sula', 1973, 'Fiction', 'Christian Bourgois'),
    ('Toni Morrison', 'Song of Solomon', 1977, 'Fiction', 'Christian Bourgois'),
    ('Toni Morrison', 'Tar Baby', 1981, 'Fiction', 'Christian Bourgois'),
    ('Toni Morrison', 'Beloved', 1987, 'Fiction', 'Christian Bourgois'),
    ('J.M.G. Le Clézio', 'Le Procès-verbal', 1963, 'Fiction', 'Gallimard'),
    ('J.M.G. Le Clézio', 'Désert', 1980, 'Fiction', 'Gallimard'),
    ('J.M.G. Le Clézio', 'Le Chercheur d''or', 1985, 'Fiction', 'Gallimard'),
    ('J.M.G. Le Clézio', 'Onitsha', 1991, 'Fiction', 'Gallimard'),
    ('J.M.G. Le Clézio', 'Étoile errante', 1992, 'Fiction', 'Gallimard'),
    ('Patrick Modiano', 'La Place de l''Étoile', 1968, 'Fiction', 'Gallimard'),
    ('Patrick Modiano', 'Les Boulevards de ceinture', 1972, 'Fiction', 'Gallimard'),
    ('Patrick Modiano', 'Rue des Boutiques Obscures', 1978, 'Fiction', 'Gallimard'),
    ('Patrick Modiano', 'Dora Bruder', 1997, 'Fiction', 'Gallimard'),
    ('Patrick Modiano', 'Un pedigree', 2005, 'Fiction', 'Gallimard'),
    ('Michel Houellebecq', 'Extension du domaine de la lutte', 1994, 'Fiction', 'Flammarion'),
    ('Michel Houellebecq', 'Les Particules élémentaires', 1998, 'Fiction', 'Flammarion'),
    ('Michel Houellebecq', 'Plateforme', 2001, 'Fiction', 'Flammarion'),
    ('Michel Houellebecq', 'La Possibilité d''une île', 2005, 'Fiction', 'Flammarion'),
    ('Michel Houellebecq', 'La Carte et le Territoire', 2010, 'Fiction', 'Flammarion'),
    ('Amélie Nothomb', 'Hygiène de l''assassin', 1992, 'Fiction', 'Albin Michel'),
    ('Amélie Nothomb', 'Le Sabotage amoureux', 1993, 'Fiction', 'Albin Michel'),
    ('Amélie Nothomb', 'Stupeur et Tremblements', 1999, 'Fiction', 'Albin Michel'),
    ('Amélie Nothomb', 'Métaphysique des tubes', 2000, 'Fiction', 'Albin Michel'),
    ('Amélie Nothomb', 'Cosmétique de l''ennemi', 2001, 'Fiction', 'Albin Michel'),

    -- Philosophie
    ('Platon', 'The Republic', -375, 'Philosophie', 'Flammarion'),
    ('Platon', 'The Symposium', -385, 'Philosophie', 'Flammarion'),
    ('Platon', 'Phaedo', -360, 'Philosophie', 'Flammarion'),
    ('Platon', 'Apology', -399, 'Philosophie', 'Flammarion'),
    ('Platon', 'Crito', -360, 'Philosophie', 'Flammarion'),
    ('Aristote', 'Nicomachean Ethics', -340, 'Philosophie', 'Vrin'),
    ('Aristote', 'Politics', -350, 'Philosophie', 'Vrin'),
    ('Aristote', 'Metaphysics', -350, 'Philosophie', 'Vrin'),
    ('Aristote', 'Poetics', -335, 'Philosophie', 'Vrin'),
    ('Aristote', 'Rhetoric', -322, 'Philosophie', 'Vrin'),
    ('René Descartes', 'Discourse on the Method', 1637, 'Philosophie', 'Vrin'),
    ('René Descartes', 'Meditations on First Philosophy', 1641, 'Philosophie', 'Vrin'),
    ('René Descartes', 'Principles of Philosophy', 1644, 'Philosophie', 'Vrin'),
    ('René Descartes', 'Passions of the Soul', 1649, 'Philosophie', 'Vrin'),
    ('René Descartes', 'Rules for the Direction of the Mind', 1628, 'Philosophie', 'Vrin'),
    ('Emmanuel Kant', 'Critique of Pure Reason', 1781, 'Philosophie', 'Vrin'),
    ('Emmanuel Kant', 'Critique of Practical Reason', 1788, 'Philosophie', 'Vrin'),
    ('Emmanuel Kant', 'Critique of Judgment', 1790, 'Philosophie', 'Vrin'),
    ('Emmanuel Kant', 'Groundwork of the Metaphysics of Morals', 1785, 'Philosophie', 'Vrin'),
    ('Emmanuel Kant', 'Metaphysics of Morals', 1797, 'Philosophie', 'Vrin'),
    ('Friedrich Nietzsche', 'The Birth of Tragedy', 1872, 'Philosophie', 'Gallimard'),
    ('Friedrich Nietzsche', 'Thus Spoke Zarathustra', 1883, 'Philosophie', 'Gallimard'),
    ('Friedrich Nietzsche', 'Beyond Good and Evil', 1886, 'Philosophie', 'Gallimard'),
    ('Friedrich Nietzsche', 'On the Genealogy of Morality', 1887, 'Philosophie', 'Gallimard'),
    ('Friedrich Nietzsche', 'The Antichrist', 1888, 'Philosophie', 'Gallimard'),
    ('Jean-Paul Sartre', 'Nausea', 1938, 'Philosophie', 'Gallimard'),
    ('Jean-Paul Sartre', 'Being and Nothingness', 1943, 'Philosophie', 'Gallimard'),
    ('Jean-Paul Sartre', 'No Exit', 1944, 'Philosophie', 'Gallimard'),
    ('Jean-Paul Sartre', 'The Flies', 1943, 'Philosophie', 'Gallimard'),
    ('Jean-Paul Sartre', 'The Age of Reason', 1945, 'Philosophie', 'Gallimard'),
    ('Simone de Beauvoir', 'She Came to Stay', 1943, 'Philosophie', 'Gallimard'),
    ('Simone de Beauvoir', 'The Blood of Others', 1945, 'Philosophie', 'Gallimard'),
    ('Simone de Beauvoir', 'All Men Are Mortal', 1946, 'Philosophie', 'Gallimard'),
    ('Simone de Beauvoir', 'The Second Sex', 1949, 'Philosophie', 'Gallimard'),
    ('Simone de Beauvoir', 'The Mandarins', 1954, 'Philosophie', 'Gallimard'),
    ('Michel Foucault', 'Madness and Civilization', 1961, 'Philosophie', 'Gallimard'),
    ('Michel Foucault', 'The Birth of the Clinic', 1963, 'Philosophie', 'Gallimard'),
    ('Michel Foucault', 'The Order of Things', 1966, 'Philosophie', 'Gallimard'),
    ('Michel Foucault', 'Discipline and Punish', 1975, 'Philosophie', 'Gallimard'),
    ('Michel Foucault', 'The History of Sexuality', 1976, 'Philosophie', 'Gallimard'),
    ('Hannah Arendt', 'The Origins of Totalitarianism', 1951, 'Philosophie', 'Gallimard'),
    ('Hannah Arendt', 'The Human Condition', 1958, 'Philosophie', 'Gallimard'),
    ('Hannah Arendt', 'Eichmann in Jerusalem', 1963, 'Philosophie', 'Gallimard'),
    ('Hannah Arendt', 'On Revolution', 1963, 'Philosophie', 'Gallimard'),
    ('Hannah Arendt', 'Men in Dark Times', 1968, 'Philosophie', 'Gallimard'),
    ('Albert Camus', 'The Stranger', 1942, 'Philosophie', 'Gallimard'),
    ('Albert Camus', 'The Plague', 1947, 'Philosophie', 'Gallimard'),
    ('Albert Camus', 'The Fall', 1956, 'Philosophie', 'Gallimard'),
    ('Albert Camus', 'The Myth of Sisyphus', 1942, 'Philosophie', 'Gallimard'),
    ('Albert Camus', 'The Rebel', 1951, 'Philosophie', 'Gallimard'),

    -- Poésie
    ('Charles Baudelaire', 'Les Fleurs du mal', 1857, 'Poésie', 'Livre de Poche'),
    ('Charles Baudelaire', 'Le Spleen de Paris', 1869, 'Poésie', 'Livre de Poche'),
    ('Charles Baudelaire', 'Les Paradis artificiels', 1860, 'Poésie', 'Livre de Poche'),
    ('Charles Baudelaire', 'La Fanfarlo', 1847, 'Poésie', 'Livre de Poche'),
    ('Charles Baudelaire', 'Journaux intimes', 1887, 'Poésie', 'Livre de Poche'),
    ('Arthur Rimbaud', 'Poésies', 1870, 'Poésie', 'Livre de Poche'),
    ('Arthur Rimbaud', 'Une saison en enfer', 1873, 'Poésie', 'Livre de Poche'),
    ('Arthur Rimbaud', 'Illuminations', 1886, 'Poésie', 'Livre de Poche'),
    ('Arthur Rimbaud', 'Le Bateau ivre', 1871, 'Poésie', 'Livre de Poche'),
    ('Arthur Rimbaud', 'Lettres', 1891, 'Poésie', 'Livre de Poche'),
    ('Paul Verlaine', 'Poèmes saturniens', 1866, 'Poésie', 'Livre de Poche'),
    ('Paul Verlaine', 'Fêtes galantes', 1869, 'Poésie', 'Livre de Poche'),
    ('Paul Verlaine', 'La Bonne Chanson', 1870, 'Poésie', 'Livre de Poche'),
    ('Paul Verlaine', 'Romances sans paroles', 1874, 'Poésie', 'Livre de Poche'),
    ('Paul Verlaine', 'Sagesse', 1880, 'Poésie', 'Livre de Poche'),
    ('Victor Hugo (Poète)', 'Les Orientales', 1829, 'Poésie', 'Livre de Poche'),
    ('Victor Hugo (Poète)', 'Les Feuilles d''automne', 1831, 'Poésie', 'Livre de Poche'),
    ('Victor Hugo (Poète)', 'Les Chants du crépuscule', 1835, 'Poésie', 'Livre de Poche'),
    ('Victor Hugo (Poète)', 'Les Voix intérieures', 1837, 'Poésie', 'Livre de Poche'),
    ('Victor Hugo (Poète)', 'Les Rayons et les Ombres', 1840, 'Poésie', 'Livre de Poche'),
    ('Guillaume Apollinaire', 'Alcools', 1913, 'Poésie', 'Gallimard'),
    ('Guillaume Apollinaire', 'Calligrammes', 1918, 'Poésie', 'Gallimard'),
    ('Guillaume Apollinaire', 'Le Poète assassiné', 1916, 'Poésie', 'Gallimard'),
    ('Guillaume Apollinaire', 'Les Mamelles de Tirésias', 1917, 'Poésie', 'Gallimard'),
    ('Guillaume Apollinaire', 'Vitam impendere amori', 1917, 'Poésie', 'Gallimard'),
    ('Emily Dickinson', 'Poems', 1890, 'Poésie', 'Dover'),
    ('Emily Dickinson', 'The Complete Poems', 1924, 'Poésie', 'Dover'),
    ('Emily Dickinson', 'The Single Hound', 1914, 'Poésie', 'Dover'),
    ('Emily Dickinson', 'Bolts of Melody', 1945, 'Poésie', 'Dover'),
    ('Emily Dickinson', 'Final Harvest', 1961, 'Poésie', 'Dover'),
    ('Walt Whitman', 'Leaves of Grass', 1855, 'Poésie', 'Penguin'),
    ('Walt Whitman', 'Drum-Taps', 1865, 'Poésie', 'Penguin'),
    ('Walt Whitman', 'Democratic Vistas', 1871, 'Poésie', 'Penguin'),
    ('Walt Whitman', 'Memoranda During the War', 1875, 'Poésie', 'Penguin'),
    ('Walt Whitman', 'Specimen Days', 1882, 'Poésie', 'Penguin'),
    ('Pablo Neruda', 'Twenty Love Poems and a Song of Despair', 1924, 'Poésie', 'Gallimard'),
    ('Pablo Neruda', 'Residence on Earth', 1933, 'Poésie', 'Gallimard'),
    ('Pablo Neruda', 'Canto General', 1950, 'Poésie', 'Gallimard'),
    ('Pablo Neruda', 'Elemental Odes', 1954, 'Poésie', 'Gallimard'),
    ('Pablo Neruda', '100 Love Sonnets', 1959, 'Poésie', 'Gallimard'),
    ('Rainer Maria Rilke', 'The Book of Images', 1902, 'Poésie', 'Seuil'),
    ('Rainer Maria Rilke', 'New Poems', 1907, 'Poésie', 'Seuil'),
    ('Rainer Maria Rilke', 'Duino Elegies', 1923, 'Poésie', 'Seuil'),
    ('Rainer Maria Rilke', 'Sonnets to Orpheus', 1923, 'Poésie', 'Seuil'),
    ('Rainer Maria Rilke', 'Letters to a Young Poet', 1929, 'Poésie', 'Seuil'),
    ('Jacques Prévert', 'Paroles', 1946, 'Poésie', 'Folio'),
    ('Jacques Prévert', 'Spectacle', 1951, 'Poésie', 'Folio'),
    ('Jacques Prévert', 'La Pluie et le beau temps', 1955, 'Poésie', 'Folio'),
    ('Jacques Prévert', 'Histoires', 1963, 'Poésie', 'Folio'),
    ('Jacques Prévert', 'Fatras', 1966, 'Poésie', 'Folio'),

    -- Théâtre
    ('William Shakespeare', 'Hamlet', 1603, 'Théâtre', 'Folio'),
    ('William Shakespeare', 'Romeo and Juliet', 1597, 'Théâtre', 'Folio'),
    ('William Shakespeare', 'Macbeth', 1623, 'Théâtre', 'Folio'),
    ('William Shakespeare', 'Othello', 1622, 'Théâtre', 'Folio'),
    ('William Shakespeare', 'King Lear', 1608, 'Théâtre', 'Folio'),
    ('Molière', 'Tartuffe', 1664, 'Théâtre', 'Livre de Poche'),
    ('Molière', 'Don Juan', 1665, 'Théâtre', 'Livre de Poche'),
    ('Molière', 'The Misanthrope', 1666, 'Théâtre', 'Livre de Poche'),
    ('Molière', 'The Miser', 1668, 'Théâtre', 'Livre de Poche'),
    ('Molière', 'The Imaginary Invalid', 1673, 'Théâtre', 'Livre de Poche'),
    ('Jean Racine', 'Andromaque', 1667, 'Théâtre', 'Livre de Poche'),
    ('Jean Racine', 'Britannicus', 1669, 'Théâtre', 'Livre de Poche'),
    ('Jean Racine', 'Bérénice', 1670, 'Théâtre', 'Livre de Poche'),
    ('Jean Racine', 'Iphigénie', 1674, 'Théâtre', 'Livre de Poche'),
    ('Jean Racine', 'Phèdre', 1677, 'Théâtre', 'Livre de Poche'),
    ('Pierre Corneille', 'Le Cid', 1637, 'Théâtre', 'Livre de Poche'),
    ('Pierre Corneille', 'Horace', 1640, 'Théâtre', 'Livre de Poche'),
    ('Pierre Corneille', 'Cinna', 1641, 'Théâtre', 'Livre de Poche'),
    ('Pierre Corneille', 'Polyeucte', 1642, 'Théâtre', 'Livre de Poche'),
    ('Pierre Corneille', 'Le Menteur', 1644, 'Théâtre', 'Livre de Poche'),
    ('Samuel Beckett', 'Waiting for Godot', 1953, 'Théâtre', 'Minuit'),
    ('Samuel Beckett', 'Endgame', 1957, 'Théâtre', 'Minuit'),
    ('Samuel Beckett', 'Krapp''s Last Tape', 1958, 'Théâtre', 'Minuit'),
    ('Samuel Beckett', 'Happy Days', 1961, 'Théâtre', 'Minuit'),
    ('Samuel Beckett', 'Play', 1963, 'Théâtre', 'Minuit'),
    ('Eugène Ionesco', 'The Bald Soprano', 1950, 'Théâtre', 'Gallimard'),
    ('Eugène Ionesco', 'The Lesson', 1951, 'Théâtre', 'Gallimard'),
    ('Eugène Ionesco', 'The Chairs', 1952, 'Théâtre', 'Gallimard'),
    ('Eugène Ionesco', 'Rhinoceros', 1959, 'Théâtre', 'Gallimard'),
    ('Eugène Ionesco', 'Exit the King', 1962, 'Théâtre', 'Gallimard'),
    ('Anton Tchekhov', 'The Seagull', 1896, 'Théâtre', 'Actes Sud'),
    ('Anton Tchekhov', 'Uncle Vanya', 1898, 'Théâtre', 'Actes Sud'),
    ('Anton Tchekhov', 'Three Sisters', 1901, 'Théâtre', 'Actes Sud'),
    ('Anton Tchekhov', 'The Cherry Orchard', 1904, 'Théâtre', 'Actes Sud'),
    ('Anton Tchekhov', 'Ivanov', 1887, 'Théâtre', 'Actes Sud'),
    ('Tennessee Williams', 'The Glass Menagerie', 1944, 'Théâtre', 'Robert Laffont'),
    ('Tennessee Williams', 'A Streetcar Named Desire', 1947, 'Théâtre', 'Robert Laffont'),
    ('Tennessee Williams', 'Cat on a Hot Tin Roof', 1955, 'Théâtre', 'Robert Laffont'),
    ('Tennessee Williams', 'Orpheus Descending', 1957, 'Théâtre', 'Robert Laffont'),
    ('Tennessee Williams', 'Sweet Bird of Youth', 1959, 'Théâtre', 'Robert Laffont'),
    ('Bertolt Brecht', 'The Threepenny Opera', 1928, 'Théâtre', 'L''Arche'),
    ('Bertolt Brecht', 'Mother Courage and Her Children', 1941, 'Théâtre', 'L''Arche'),
    ('Bertolt Brecht', 'Life of Galileo', 1943, 'Théâtre', 'L''Arche'),
    ('Bertolt Brecht', 'The Good Person of Szechwan', 1943, 'Théâtre', 'L''Arche'),
    ('Bertolt Brecht', 'The Caucasian Chalk Circle', 1948, 'Théâtre', 'L''Arche'),
    ('Edmond Rostand', 'Cyrano de Bergerac', 1897, 'Théâtre', 'Livre de Poche'),
    ('Edmond Rostand', 'L''Aiglon', 1900, 'Théâtre', 'Livre de Poche'),
    ('Edmond Rostand', 'Chantecler', 1910, 'Théâtre', 'Livre de Poche'),
    ('Edmond Rostand', 'Les Romanesques', 1894, 'Théâtre', 'Livre de Poche'),
    ('Edmond Rostand', 'La Princesse Lointaine', 1895, 'Théâtre', 'Livre de Poche')
)
INSERT INTO temp_livres_data (isbn, auteur_nom, titre, annee, categorie, editeur)
SELECT 
    '978' || lpad((row_number() OVER (ORDER BY auteur_nom, titre))::text, 10, '0'),
    auteur_nom, titre, annee, categorie, editeur
FROM raw_data;

-- Insert into livres
INSERT INTO livres (isbn, titre, categorie, annee_publication, editeur, langue, nb_pages, format, nb_exemplaires, localisation, etat)
SELECT 
    isbn, 
    titre, 
    categorie, 
    annee, 
    editeur, 
    'Français', 
    (floor(random() * 500) + 100)::int, 
    'Poche', 
    (floor(random() * 10) + 1)::int, 
    'Rayon ' || chr(65 + floor(random() * 26)::int) || '-' || floor(random() * 100)::int, 
    'Bon'
FROM temp_livres_data;

-- Insert into livre_auteurs
INSERT INTO livre_auteurs (livre_isbn, auteur_id)
SELECT t.isbn, a.id
FROM temp_livres_data t
JOIN auteurs a ON t.auteur_nom = a.nom_complet;

-- Cleanup
DROP TABLE temp_livres_data;
